libtls: Add HKDF implementation for TLS 1.3
bytinbit/strongswan pull request #35
Opened 2020-04-29 14:33 UTC by ryru

TLS 1.3 uses HMAC-based Extract-and-Expand Key Derivation Function (HKDF)
as defined in RFC 5869 to compute traffic secrets.

2020-04-29 15:47 UTC, strongX509 reviewed
## test_hkdf.c

Line 389: /* Generate client handshake traffic secret */
Line 398: /* Generate server handshake traffic secret */
Copy & paste error: Generate client/server application traffic secret

## tls_hkdf.c

Line 17: #include "../libstrongswan/utils/chunk.h"
Line 18: #include <utils/chunk.h>
Line 17 is equivalent to Line 18 and can be removed

Error messages are usually logged with DBG1 level

Line 164: /* HKDFLabel */
Instead of memcpy() of chunks the chunk_cat() function could be used

Line 204: static bool move_to_phase_1(private_tls_hkdf_t *this)
Line 229: static bool move_to_phase_2(private_tls_hkdf_t *this)
Line 279: static bool move_to_phase_3(private_tls_hkdf_t *this)
Use switch statement instead of multiple ifs

Line 334: METHOD(tls_hkdf_t, set_shared_secret, bool, private_tls_hkdf_t *this, chunk_t *shared_secret)
Better:
if (!shared_secret)
{
  DBG1(DBG_TLS, "no shared secret provided);
 return FALSE;
}
this->shared_secret = shared_secret;
return TRUE;
It might even not be necessary to check for an empty secret

Line 348: METHOD(tls_hkdf_t, generate_secret,
A lot of duplicated code. Use array of label names and bundle cases for phase 1, 2, 3,

2020-04-29 20:30 UTC, ryru commented
> Line 164: /* HKDFLabel */
> Instead of memcpy() of chunks the chunk_cat() function could be used

Still open, unsure how to use `chunk_cat()` correctly.

2020-04-30 11:25 UTC, tobiasbrunner requested changes
Please try to adhere to the maximum line length of 80 characters (I only pointed out selected lines with this issue).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tests/suites/test_hkdf.c
> +	ck_assert(chunk_equals(expected_client_handshake_traffic_secret, c_secret));
Use the following instead as it prints the contents if the chunks are not equal:
```suggestion
	ck_assert_chunk_eq(expected_client_handshake_traffic_secret, c_secret);
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tests/suites/test_hkdf.c
> +		/* df4a291baa1eb7cfa6934b29b474baad2697e29f1f920dcc77c8a0a088447624 */
No need for these comments as we can clearly see the values below.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +#include "tls_hkdf.h"
Add an empty line after this one. Typically it's system headers, empty line, local headers (with ""), empty line, library headers (with <>).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +#include <utils/chunk.h>
If you include library.h, you can remove this one.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +/* HKDF-Extract(this->salt, this->ikm) -> this->prk */
No need for `this->` here, just write it as it is in [RFC 5869](https://tools.ietf.org/html/rfc5869) and maybe even reference the RFC, that is, write something like:
```suggestion
/**
 * Step 1: Extract, as defined in RFC 5869, section 2.2:
 * HKDF-Extract(salt, IKM) -> PRK
 */

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +static bool extract(private_tls_hkdf_t *this, chunk_t *salt, chunk_t *ikm, chunk_t *prk)
Neither `salt`, nor `ikm` should be pointers here, only `prk` is returned.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	DBG3(DBG_TLS, "PRK: %B", prk);
This should probably be `DBG4` as the PRK is sensitive key material.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +/* HKDF-Expand(this->prk, this->info, this->L) -> this->okm */
Same as above:
```suggestion
/**
 * Step 2: Expand as defined in RFC 5869, section 2.3:
 * HKDF-Expand(PRK, info, L) -> OKM
 */
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +static bool expand(private_tls_hkdf_t *this, chunk_t *prk, chunk_t *info, size_t lenght, chunk_t *okm)
Likewise, only chunks that are returned should be pointers, unless...

Also, it's `length`, not `lenght`.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +		chunk_free(&this->info);
...you actually want to refer to a specific chunk and free/clear it here. But either use the chunks directly via `this`, or pass them as arguments, don't do both. Since this member variable is not really necessary, just pass this chunk and free it in `expand_label()`.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +static bool expand_label(private_tls_hkdf_t *this, chunk_t *secret, chunk_t *label, chunk_t *context, uint16_t length, chunk_t *key)
This line looks too long. And please add a comment. Plus chunk pointers again. Same goes for all the functions that follow.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	size_t offset = 0;
Declare the variables at the start of the function (you can assign values if short like this, but not like the one on the next line).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	size_t chunk_len = 2 + 1 + label->len + 1 + context->len;
Not really necessary as it's used only once. It might help to add a comment that explains the structure of the label and what the magic numbers represent (they are not necessary if a `bio_writer_t` is used, see below).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	offset += context->len;
Instead of doing this manually, it would be easier to use `bio_writer_t` for this. No need to keep track of offsets or manual mapping of integers, the label and context can be written directly with `write_data8()`, the length of the allocated chunk would also not have to be calculated beforehand. And as mentioned before, it does not have to be a member variable either i.e.
```suggestion
	writer = bio_writer_create(0);
	writer->write_uint16(writer, length);
	writer->write_data8(writer, label);
	writer->write_data8(writer, context);
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	size_t chunk_len = this->L;
No need for this variable.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	DBG3(DBG_TLS, "OKM: %B", okm);
Should be `DBG4`.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t context = chunk_alloca(chunk_len);
Don't use `chunk_alloca()` here if you use `allocate_hash()` afterwards (no need to reserve space on the stack or determine the length before). You could theoretically use `chunk_alloca()` combined with `get_hash()`, then you wouldn't have to free it afterwards.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	if (!this->hasher || !this->hasher->allocate_hash(this->hasher, *messages, &context))
Add a newline after `||` as the line is too long.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +				DBG1(DBG_TLS, "unable extract PRK");
"to" is missing.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +		case HKDF_PHASE_1:
Whenever `break;` is omitted on purpose there should be a comment (e.g. `/* fall-through */`). Also, shouldn't the return value be checked?

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +			empty = chunk_empty;
No need for this if you don't pass it as pointer, just use `chunk_empty` in the call below.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +				this->ikm.len = this->shared_secret->len;
This looks like `this->ikm = chunk_clone(this->shared_secret);`. Is it strictly necessary to have two member variables for these chunks?

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +static bool move_to_phase_3(private_tls_hkdf_t *this)
See my comments for `move_to_phase_2()` above.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +
```suggestion
	chunk_copy_pad(*secret, *key, 0);
```
Key should not be a pointer, though.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	this->shared_secret = shared_secret;
Should this be cloned, adopted or just used? Any previous value be cleared (also in `destroy()`)? It should be clearly documented in the header who is responsible for this data (it might be risky to just use it if other methods can be called unrelated to this). Also, as mentioned before, it might be possible to just set `this->ikm` here.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t label_name;
New line missing after this.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +METHOD(tls_hkdf_t, set_shared_secret, bool, private_tls_hkdf_t *this, chunk_t *shared_secret)
Add a newline after the return type (`bool,`) and indent the line with one tab, also for the other METHODs.

```suggestion
METHOD(tls_hkdf_t, set_shared_secret, bool,
	private_tls_hkdf_t *this, chunk_t *shared_secret)
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	label_name = chunk_from_str(hkdf_labels[label]);
This should be done after the switch statement, so we are sure the label is valid.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +				DBG1(DBG_TLS, "unable to move to phase 1.");
Don't terminate log messages with a dot.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	this->L = length;
Move this after the local variables (if still necessary, see other comments regarding `this->L`).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	if (!secret)
Could be combined with the `if` statement below (`if (secret && !write_...)`). However, as mentioned above, there should probably not be a return value for that call, so maybe just wrap it with `if (secret)`.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	if (!key)
Same as above. No log message necessary either.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_clear(&result);
Should have been done also if the above call failed, but if the return value is gone, this is OK.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +METHOD(tls_hkdf_t, derive_iv, bool, private_tls_hkdf_t *this, bool is_server, size_t length, chunk_t *iv)
See comments for `derive_key()` above. It should be possible to move most of the code into a shared helper function.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +		.L = 32,
Shouldn't `L` (or rather the salt length below) be be based on the output length of the hash function? I feel this member variable is unnecessary as the length is either passed as parameter (key/IV), or based on the hash function.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +		.prf = lib->crypto->create_prf(lib->crypto, PRF_HMAC_SHA2_256),
This should be based on the hash algorithm. There is currently no helper function like `pseudo_random_function_from_hasher()` for this, though (there is `hasher_algorithm_from_prf()` for the other direction). So maybe use a switch statement above `INIT()` to determine the PRF algorithm based on the hash algorithm for now.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	if (!this->hasher)
Also check if the PRF was instantiated.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	this->hasher->destroy(this->hasher);
`DESTROY_IF()` as they might not be defined when called from the constructor.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +		chunk_create_clone(psk->ptr, this->ikm);
```suggestion
		this->ikm = chunk_clone(psk);
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.h
> +	bool (*derive_iv)(tls_hkdf_t *this, bool is_server, size_t length, chunk_t *iv);
Document that memory for the key/IV is allocated on success.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t *psk;
Unused

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	size_t hash_length;
Unused

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t *shared_secret;
May not be necessary (see other comments).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	size_t L;
May not be necessary (see other comments).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t salt;
This doesn't seem necessary, just initialize `this->okm` to hash length zero bytes.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +			if (!extract(this, &this->salt, &this->ikm, &this->prk))
The only location where `this->salt` is used. Either just use `this->okm`, like everywhere else and initialize it to hash length zeroes in the constructor, or create a local chunk of appropriate length. For instance, with
```c
uint8_t salt[this->hasher->get_hash_size(this->hasher)] = {0};
if (!extract(this, chunk_create(salt, sizeof(salt)), ...)
```
or
```c
chunk_t salt = chunk_alloca(this->hasher->get_hash_size(this->hasher));
chunk_copy_pad(salt, chunk_empty, 0);
if (!extract(this, salt, ...)
```
As mentioned above, only output parameters should be passed as pointers.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	memset(this->salt.ptr, 0, this->salt.len);
Instead initialize `this->okm` and use the output length of the hasher (but as mentioned, the salt value could also be allocated directly on the stack where it's required).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tests/suites/test_hkdf.c
> + *
```suggestion
 * HSR Hochschule fuer Technik Rapperswil
 *
```
Also in the other copyright headers.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t info;
No need for this member variable. The only user is `expand()`, which is only called from `expand_label()` that also generates this chunk. So just pass the chunk to it and destroy it afterwards.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	prf_plus_t *prf_plus;
Not necessary, it's only used transiently in `expand()`. Just create it there and destroy it directly after use.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	this->prf_plus = prf_plus_create(this->prf, TRUE, *info);
As mentioned above, just use a local variable for this. Also make sure the constructor does not return NULL (e.g. in the if statement below: `if (!prf_plus || !prf_plus->allocate...)`, then use `DESTROY_IF(prf_plus)`).

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	return TRUE;
Check the return value and pass it to the caller. And with the writer change above this would result in something  like this:
```suggestion
	success = expand(this, secret, writer->get_buf(writer), length, key);
	writer->destroy(writer);
	return success;
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	expand_label(this, &this->prk, label, &context, this->L, &this->okm);
Pass the return value to the caller.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +			);
This only works with SHA-256. It's similar to the salt above, you could either clear `this->ikm` and set it to a hash length chunk of zeroes and then pass that in the call below, or create such a chunk locally here on the stack.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	*secret = chunk_alloc(this->L);
```suggestion
	*secret = chunk_alloc(this->hasher->get_hash_size(this->hasher));
```

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +static bool write_key_to_caller_secret(private_tls_hkdf_t *this, chunk_t *key, chunk_t *secret)
Why does this return a `bool`? The name is also a bit verbose :)

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.c
> +	chunk_t messages = chunk_empty;
Not necessary.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.h
> +	bool (*set_shared_secret)(tls_hkdf_t *this, chunk_t *shared_secret);
The secret should not be passed as pointer. And as mentioned in the implementation, it should be clearly stated who is responsible for the passed secret.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.h
> +	bool (*generate_secret)(tls_hkdf_t *this, enum tls_hkdf_labels_t label, chunk_t *messages, chunk_t *secret);
The messages should not be passed as pointer.

2020-04-30 11:25 UTC, tobiasbrunner commented on src/libtls/tls_hkdf.h
> +tls_hkdf_t *tls_hkdf_create(hash_algorithm_t hash_algorithm, chunk_t *psk);
No pointer here either.

2020-05-02 11:30 UTC, bytinbit commented
Remove `bool is_server` method argument, it is not used in any public method.

2020-05-21 05:57 UTC, merged